//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ServiceModel.Samples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ServiceModel.Samples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginAcceptChannel invoked..
        /// </summary>
        internal static string BeginAcceptChannel {
            get {
                return ResourceManager.GetString("BeginAcceptChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginTryReceiveRequest is invoked in session: {0}.
        /// </summary>
        internal static string BeginTryReceiveInvoked {
            get {
                return ResourceManager.GetString("BeginTryReceiveInvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to httpCookieSession.
        /// </summary>
        internal static string ConfiguredSectionName {
            get {
                return ResourceManager.GetString("ConfiguredSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot dequeue a channel, the listner is not opened..
        /// </summary>
        internal static string DequeueFailedListenerNotOpen {
            get {
                return ResourceManager.GetString("DequeueFailedListenerNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndAcceptChannel invoked..
        /// </summary>
        internal static string EndAcceptChannel {
            get {
                return ResourceManager.GetString("EndAcceptChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndAcceptChannel is returning null. Listener seems to be closed!.
        /// </summary>
        internal static string EndAcceptChannelReturnsNull {
            get {
                return ResourceManager.GetString("EndAcceptChannelReturnsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndAcceptChannel returns a session channel..
        /// </summary>
        internal static string EndAcceptChannelReturnsOK {
            get {
                return ResourceManager.GetString("EndAcceptChannelReturnsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener is trying to enqueue a message for session: {0}. Unfortunatly it is not opened..
        /// </summary>
        internal static string EnqueueFailed {
            get {
                return ResourceManager.GetString("EnqueueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchangeTerminate.
        /// </summary>
        internal static string ExchangeTerminateAttribute {
            get {
                return ResourceManager.GetString("ExchangeTerminateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string ExchangeTerminateAttributeValue {
            get {
                return ResourceManager.GetString("ExchangeTerminateAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchangeTerminateMessage.
        /// </summary>
        internal static string exchangeTerminateMessageProperty {
            get {
                return ResourceManager.GetString("exchangeTerminateMessageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to httpRequest.
        /// </summary>
        internal static string httpRequestProperties {
            get {
                return ResourceManager.GetString("httpRequestProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to httpResponse.
        /// </summary>
        internal static string httpResponseProperties {
            get {
                return ResourceManager.GetString("httpResponseProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpCookieSessionBinding works only with {0}..
        /// </summary>
        internal static string HttpTransportNotFound {
            get {
                return ResourceManager.GetString("HttpTransportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpCookieReplySessionChannelListener aborted..
        /// </summary>
        internal static string ListenerAborted {
            get {
                return ResourceManager.GetString("ListenerAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpCookieReplySessionChannelListener is closing..
        /// </summary>
        internal static string ListenerClosing {
            get {
                return ResourceManager.GetString("ListenerClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpCookieReplySessionChannelListener opend..
        /// </summary>
        internal static string ListenerOpened {
            get {
                return ResourceManager.GetString("ListenerOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message enqueued to session {0}.
        /// </summary>
        internal static string MessageEnqueued {
            get {
                return ResourceManager.GetString("MessageEnqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener started the message pump..
        /// </summary>
        internal static string MessagePumpStarted {
            get {
                return ResourceManager.GetString("MessagePumpStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://samples.microsoft.com/wcf/mhsc/policy.
        /// </summary>
        internal static string mhsc {
            get {
                return ResourceManager.GetString("mhsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to httpSessionCookie.
        /// </summary>
        internal static string mhscElementName {
            get {
                return ResourceManager.GetString("mhscElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string NotImplementedException {
            get {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MetadataExporter object passed to the ExporterBindingElement is null..
        /// </summary>
        internal static string NullExporter {
            get {
                return ResourceManager.GetString("NullExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PolicyConversionContext object passed to the ExporterBindingElement is null..
        /// </summary>
        internal static string NullPolicyContext {
            get {
                return ResourceManager.GetString("NullPolicyContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener quits receiving from the inner channel..
        /// </summary>
        internal static string QuitReceiving {
            get {
                return ResourceManager.GetString("QuitReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TryReceive invoked whike shutting down..
        /// </summary>
        internal static string ReceiveInvokedWhileShuttingDown {
            get {
                return ResourceManager.GetString("ReceiveInvokedWhileShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session cleaned up. Session id: {0}.
        /// </summary>
        internal static string RemoveChannel {
            get {
                return ResourceManager.GetString("RemoveChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener received a request from the inner channel..
        /// </summary>
        internal static string RequestReceived {
            get {
                return ResourceManager.GetString("RequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session with id: {0} is closed..
        /// </summary>
        internal static string SessionClosedMessage {
            get {
                return ResourceManager.GetString("SessionClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session created with id: {0}..
        /// </summary>
        internal static string SessionCreatedMessage {
            get {
                return ResourceManager.GetString("SessionCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired.
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET_SessionId={0}.
        /// </summary>
        internal static string SessionIdFormat {
            get {
                return ResourceManager.GetString("SessionIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New session channel is ready to pick up..
        /// </summary>
        internal static string SessionReady {
            get {
                return ResourceManager.GetString("SessionReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive timed out. Session {0} is trying to tear down..
        /// </summary>
        internal static string SessionTimedOut {
            get {
                return ResourceManager.GetString("SessionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sessionTimeout.
        /// </summary>
        internal static string sessionTimeoutProperty {
            get {
                return ResourceManager.GetString("sessionTimeoutProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://samples.microsoft.com/wcf/httpcookiesession/terminateack.
        /// </summary>
        internal static string TerminateAck {
            get {
                return ResourceManager.GetString("TerminateAck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://samples.microsoft.com/wcf/httpcookiesession/terminate.
        /// </summary>
        internal static string TerminateRequestAction {
            get {
                return ResourceManager.GetString("TerminateRequestAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to gracefully shutdown the session..
        /// </summary>
        internal static string TerminateRequestFailed {
            get {
                return ResourceManager.GetString("TerminateRequestFailed", resourceCulture);
            }
        }
    }
}
