//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://Microsoft.ServiceModel.Samples", ClrNamespace="Microsoft.ServiceModel.Samples")]

namespace Microsoft.ServiceModel.Samples
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Album : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double PriceField;
        
        private string TitleField;
        
        private Microsoft.ServiceModel.Samples.Track[] TracksField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.ServiceModel.Samples.Track[] Tracks
        {
            get
            {
                return this.TracksField;
            }
            set
            {
                this.TracksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Track : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DurationField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="Microsoft.ServiceModel.Samples.IAlbumService")]
    public interface IAlbumService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlbumService/GetAlbumList", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlbumService/GetAlbumListResponse")]
        Microsoft.ServiceModel.Samples.Album[] GetAlbumList();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://Microsoft.ServiceModel.Samples/IAlbumService/GetAlbumList", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlbumService/GetAlbumListResponse")]
        System.IAsyncResult BeginGetAlbumList(System.AsyncCallback callback, object asyncState);
        
        Microsoft.ServiceModel.Samples.Album[] EndGetAlbumList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlbumService/AddAlbum", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlbumService/AddAlbumResponse")]
        void AddAlbum(string title);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://Microsoft.ServiceModel.Samples/IAlbumService/AddAlbum", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlbumService/AddAlbumResponse")]
        System.IAsyncResult BeginAddAlbum(string title, System.AsyncCallback callback, object asyncState);
        
        void EndAddAlbum(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAlbumServiceChannel : Microsoft.ServiceModel.Samples.IAlbumService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AlbumServiceClient : System.ServiceModel.ClientBase<Microsoft.ServiceModel.Samples.IAlbumService>, Microsoft.ServiceModel.Samples.IAlbumService
    {
        
        public AlbumServiceClient()
        {
        }
        
        public AlbumServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AlbumServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AlbumServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AlbumServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Microsoft.ServiceModel.Samples.Album[] GetAlbumList()
        {
            return base.Channel.GetAlbumList();
        }
        
        public System.IAsyncResult BeginGetAlbumList(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetAlbumList(callback, asyncState);
        }
        
        public Microsoft.ServiceModel.Samples.Album[] EndGetAlbumList(System.IAsyncResult result)
        {
            return base.Channel.EndGetAlbumList(result);
        }
        
        public void AddAlbum(string title)
        {
            base.Channel.AddAlbum(title);
        }
        
        public System.IAsyncResult BeginAddAlbum(string title, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginAddAlbum(title, callback, asyncState);
        }
        
        public void EndAddAlbum(System.IAsyncResult result)
        {
            base.Channel.EndAddAlbum(result);
        }
    }
}

