'------------------------------------------------------------------------------
' <autogenerated>
'     This class was generated by a tool.
'     Runtime Version: 1.0.2204.14
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Imports System.Xml.Serialization

Namespace XmlSerializationHowTo
    Public Class <System.Xml.Serialization.XmlRootAttribute("purchaseOrder", [Namespace]:="http://electrocommerce.org/po", IsNullable:=false)> PurchaseOrder
        
        Public <System.Xml.Serialization.XmlElementAttribute("shipTo", Form:=System.Xml.Serialization.XmlForm.Unqualified, IsNullable:=false)> ShipTo As Address
        Public <System.Xml.Serialization.XmlElementAttribute("billTo", Form:=System.Xml.Serialization.XmlForm.Unqualified, IsNullable:=false)> BillTo As Address
        Public <System.Xml.Serialization.XmlElementAttribute("comment", Form:=System.Xml.Serialization.XmlForm.Unqualified, IsNullable:=false)> Comment As String
        Public <System.Xml.Serialization.XmlElementAttribute("items", Form:=System.Xml.Serialization.XmlForm.Unqualified, IsNullable:=false)> Items As PurchaseOrderItems
        Public <System.Xml.Serialization.XmlAttributeAttribute("orderDate", Form:=System.Xml.Serialization.XmlForm.Unqualified, DataType:="date")> OrderDate As Date
        Public <System.Xml.Serialization.XmlIgnoreAttribute()> OrderDateSpecified As Boolean
        
    End Class
    Public Class  Address
        
        Public <System.Xml.Serialization.XmlElementAttribute("name", Form:=System.Xml.Serialization.XmlForm.Unqualified, IsNullable:=false)> Name As String
        Public <System.Xml.Serialization.XmlElementAttribute("street", Form:=System.Xml.Serialization.XmlForm.Unqualified, IsNullable:=false)> Street As String
        Public <System.Xml.Serialization.XmlElementAttribute("city", Form:=System.Xml.Serialization.XmlForm.Unqualified, IsNullable:=false)> City As String
        Public <System.Xml.Serialization.XmlElementAttribute("state", Form:=System.Xml.Serialization.XmlForm.Unqualified, IsNullable:=false)> State As String
        Public <System.Xml.Serialization.XmlElementAttribute("zip", Form:=System.Xml.Serialization.XmlForm.Unqualified, IsNullable:=false)> Zip As Decimal
        Public <System.Xml.Serialization.XmlAttributeAttribute("country", Form:=System.Xml.Serialization.XmlForm.Unqualified)> Country As String
        
    End Class
    Public Class <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://electrocommerce.org/po")> PurchaseOrderItems
        
    End Class
End Namespace
