//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.30
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Working_with_XML_in_Excel.Properties.Settings.get_Default():Working_with_XML_in_E" +
    "xcel.Properties.Settings")]

namespace Working_with_XML_in_Excel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = new Settings();
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ignyte.com/webservices/ignyte.whatsshowing.webservice/moviefunctions.a" +
            "smx")]
        public string Working_with_XML_in_Excel_IgnyteTheaterMovieService_MovieInformation {
            get {
                return ((string)(this["Working_with_XML_in_Excel_IgnyteTheaterMovieService_MovieInformation"]));
            }
        }
    }
}
