//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 05-02-06 04:50 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace BiztalkWsfcDemo.Client.WebProxy
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BizTalkWscfDemoService/BiztalkWscfDemoSrvcMsgs.xsd", TypeName="getCompanyForPerson")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    [Serializable()]
    public class GetCompanyForPerson
    {
        
        /// <remarks/>
        private int id;
        
        public GetCompanyForPerson()
        {
        }
        
        public GetCompanyForPerson(int id)
        {
            this.id = id;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="id")]
        public int Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }
    }
}
