'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50215.44
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

<Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="My.Resources.Resources.get_ResourceManager():System.Resources.ResourceManager"),  _
 Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="My.Resources.Resources.get_Culture():System.Globalization.CultureInfo"),  _
 Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="My.Resources.Resources.set_Culture(System.Globalization.CultureInfo):Void")> 

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleName()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If (resourceMan Is Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.Samples.MoodOrb.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;00501&quot;,&quot;+40.922326&quot;,&quot;-072.637078&quot;,&quot;HOLTSVILLE&quot;,&quot;NY&quot;,&quot;SUFFOLK&quot;,&quot;UNIQUE&quot;
        '''&quot;00544&quot;,&quot;+40.922326&quot;,&quot;-072.637078&quot;,&quot;HOLTSVILLE&quot;,&quot;NY&quot;,&quot;SUFFOLK&quot;,&quot;UNIQUE&quot;
        '''&quot;00601&quot;,&quot;+18.165273&quot;,&quot;-066.722583&quot;,&quot;ADJUNTAS&quot;,&quot;PR&quot;,&quot;ADJUNTAS&quot;,&quot;STANDARD&quot;
        '''&quot;00602&quot;,&quot;+18.393103&quot;,&quot;-067.180953&quot;,&quot;AGUADA&quot;,&quot;PR&quot;,&quot;AGUADA&quot;,&quot;STANDARD&quot;
        '''&quot;00603&quot;,&quot;+18.455913&quot;,&quot;-067.145780&quot;,&quot;AGUADILLA&quot;,&quot;PR&quot;,&quot;AGUADILLA&quot;,&quot;STANDARD&quot;
        '''&quot;00604&quot;,&quot;+18.493520&quot;,&quot;-067.135883&quot;,&quot;AGUADILLA&quot;,&quot;PR&quot;,&quot;AGUADILLA&quot;,&quot;STANDARD&quot;
        '''&quot;00605&quot;,&quot;+18.465162&quot;,&quot;-067.141486&quot;,&quot;AGUADILLA&quot;,&quot;PR&quot;,&quot;AGUADILLA&quot;,&quot;STAND [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ZipCodeData() As String
            Get
                Return ResourceManager.GetString("ZipCodeData", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
