'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.26
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1), _
 System.Runtime.InteropServices.ComVisibleAttribute(False), _
 System.Security.Permissions.PermissionSetAttribute(System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")> _
Partial Public NotInheritable Class Sheet1
    Inherits Microsoft.Office.Tools.Excel.Worksheet
    Implements Microsoft.VisualStudio.Tools.Applications.Runtime.IStartup

    Friend WithEvents Sheet1_Print_Area As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents employeeNameNamedRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents employeeTitleNamedRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents locationNamedRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents employeeNumberNamedRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents employeePhoneNamedRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents emailAddressNamedRange As Microsoft.Office.Tools.Excel.NamedRange

    <Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private RuntimeCallback As Microsoft.VisualStudio.Tools.Applications.Runtime.IRuntimeServiceProvider

    <Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private HostItemHost As Microsoft.VisualStudio.Tools.Applications.Runtime.IHostItemProvider

    <Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private DataHost As Microsoft.VisualStudio.Tools.Applications.Runtime.ICachedDataProvider

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Public Sub New(ByVal RuntimeCallback As Microsoft.VisualStudio.Tools.Applications.Runtime.IRuntimeServiceProvider)
        MyBase.New(CType(RuntimeCallback.GetService(GetType(Microsoft.VisualStudio.Tools.Applications.Runtime.IHostItemProvider)), Microsoft.VisualStudio.Tools.Applications.Runtime.IHostItemProvider), RuntimeCallback, "Sheet1", Nothing, "Sheet1")
        Me.RuntimeCallback = RuntimeCallback
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Public Sub Initialize() Implements Microsoft.VisualStudio.Tools.Applications.Runtime.IStartup.Initialize
        Me.HostItemHost = CType(Me.RuntimeCallback.GetService(GetType(Microsoft.VisualStudio.Tools.Applications.Runtime.IHostItemProvider)), Microsoft.VisualStudio.Tools.Applications.Runtime.IHostItemProvider)
        Me.DataHost = CType(Me.RuntimeCallback.GetService(GetType(Microsoft.VisualStudio.Tools.Applications.Runtime.ICachedDataProvider)), Microsoft.VisualStudio.Tools.Applications.Runtime.ICachedDataProvider)
        Globals.Sheet1 = Me
        System.Windows.Forms.Application.EnableVisualStyles()
        Me.InitializeCachedData()
        Me.InitializeControls()
        Me.InitializeComponents()
        Me.InitializeData()
        Me.BeginInitialization()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Public Sub FinishInitialization() Implements Microsoft.VisualStudio.Tools.Applications.Runtime.IStartup.FinishInitialization
        Me.OnStartup()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Public Sub InitializeDataBindings() Implements Microsoft.VisualStudio.Tools.Applications.Runtime.IStartup.InitializeDataBindings
        Me.BindToData()
        Me.EndInitialization()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Public Overrides Sub OnShutdown() Implements Microsoft.VisualStudio.Tools.Applications.Runtime.IStartup.OnShutdown
        Me.emailAddressNamedRange.Dispose()
        Me.employeePhoneNamedRange.Dispose()
        Me.employeeNumberNamedRange.Dispose()
        Me.locationNamedRange.Dispose()
        Me.employeeTitleNamedRange.Dispose()
        Me.employeeNameNamedRange.Dispose()
        Me.Sheet1_Print_Area.Dispose()
        MyBase.OnShutdown()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeCachedData()
        If (Me.DataHost Is Nothing) Then
            Return
        End If
        If Me.DataHost.IsCacheInitialized Then
            Me.DataHost.FillCachedData(Me)
        End If
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeData()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub BindToData()
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Sub StartCaching(ByVal MemberName As String)
        Me.DataHost.StartCaching(Me, MemberName)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Sub StopCaching(ByVal MemberName As String)
        Me.DataHost.StopCaching(Me, MemberName)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Function IsCached(ByVal MemberName As String) As Boolean
        Return Me.DataHost.IsCached(Me, MemberName)
    End Function

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub BeginInitialization()
        Me.BeginInit()
        Me.Sheet1_Print_Area.BeginInit()
        Me.employeeNameNamedRange.BeginInit()
        Me.employeeTitleNamedRange.BeginInit()
        Me.locationNamedRange.BeginInit()
        Me.employeeNumberNamedRange.BeginInit()
        Me.employeePhoneNamedRange.BeginInit()
        Me.emailAddressNamedRange.BeginInit()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub EndInitialization()
        Me.emailAddressNamedRange.EndInit()
        Me.employeePhoneNamedRange.EndInit()
        Me.employeeNumberNamedRange.EndInit()
        Me.locationNamedRange.EndInit()
        Me.employeeTitleNamedRange.EndInit()
        Me.employeeNameNamedRange.EndInit()
        Me.Sheet1_Print_Area.EndInit()
        Me.EndInit()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeControls()
        Me.Sheet1_Print_Area = New Microsoft.Office.Tools.Excel.NamedRange(Me.HostItemHost, Me.RuntimeCallback, "Sheet1!Print_Area", Me, "Sheet1_Print_Area")
        Me.employeeNameNamedRange = New Microsoft.Office.Tools.Excel.NamedRange(Me.HostItemHost, Me.RuntimeCallback, "employeeNameNamedRange", Me, "employeeNameNamedRange")
        Me.employeeTitleNamedRange = New Microsoft.Office.Tools.Excel.NamedRange(Me.HostItemHost, Me.RuntimeCallback, "employeeTitleNamedRange", Me, "employeeTitleNamedRange")
        Me.locationNamedRange = New Microsoft.Office.Tools.Excel.NamedRange(Me.HostItemHost, Me.RuntimeCallback, "locationNamedRange", Me, "locationNamedRange")
        Me.employeeNumberNamedRange = New Microsoft.Office.Tools.Excel.NamedRange(Me.HostItemHost, Me.RuntimeCallback, "employeeNumberNamedRange", Me, "employeeNumberNamedRange")
        Me.employeePhoneNamedRange = New Microsoft.Office.Tools.Excel.NamedRange(Me.HostItemHost, Me.RuntimeCallback, "employeePhoneNamedRange", Me, "employeePhoneNamedRange")
        Me.emailAddressNamedRange = New Microsoft.Office.Tools.Excel.NamedRange(Me.HostItemHost, Me.RuntimeCallback, "emailAddressNamedRange", Me, "emailAddressNamedRange")
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeComponents()
        CType(Me.Sheet1_Print_Area, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.employeeNameNamedRange, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.employeeTitleNamedRange, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.locationNamedRange, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.employeeNumberNamedRange, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.employeePhoneNamedRange, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.emailAddressNamedRange, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
        '
        'Sheet1
        '
        CType(Me.Sheet1_Print_Area, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.employeeNameNamedRange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.employeeTitleNamedRange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.locationNamedRange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.employeeNumberNamedRange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.employeePhoneNamedRange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.emailAddressNamedRange, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)> _
    Private Function NeedsFill(ByVal MemberName As String) As Boolean
        Return Me.DataHost.NeedsFill(Me, MemberName)
    End Function
End Class

Partial Friend NotInheritable Class Globals

    Private Shared _Sheet1 As Sheet1

    Friend Shared Property Sheet1() As Sheet1
        Get
            Return _Sheet1
        End Get
        Set(ByVal value As Sheet1)
            If (_Sheet1 Is Nothing) Then
                _Sheet1 = value
            Else
                Throw New System.NotSupportedException
            End If
        End Set
    End Property
End Class
