'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Namespace Microsoft.ServiceModel.Samples
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://Microsoft.ServiceModel.Samples")>  _
    Public Interface IInstanceContextCalculator
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/Add", ReplyAction:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/AddResponse")>  _
        Function Add(ByVal n1 As Integer, ByVal n2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/Subtract", ReplyAction:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/SubtractResponse"& _ 
            "")>  _
        Function Subtract(ByVal n1 As Integer, ByVal n2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/Multiply", ReplyAction:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/MultiplyResponse"& _ 
            "")>  _
        Function Multiply(ByVal n1 As Integer, ByVal n2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/Divide", ReplyAction:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/DivideResponse")>  _
        Function Divide(ByVal n1 As Integer, ByVal n2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/GetInstanceConte"& _ 
            "xtInfo", ReplyAction:="http://Microsoft.ServiceModel.Samples/IInstanceContextCalculator/GetInstanceConte"& _ 
            "xtInfoResponse")>  _
        Function GetInstanceContextInfo() As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IInstanceContextCalculatorChannel
        Inherits IInstanceContextCalculator, System.ServiceModel.IClientChannel
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class InstanceContextCalculatorProxy
        Inherits System.ServiceModel.ClientBase(Of IInstanceContextCalculator)
        Implements IInstanceContextCalculator
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Add(ByVal n1 As Integer, ByVal n2 As Integer) As Integer Implements IInstanceContextCalculator.Add
            Return MyBase.Channel.Add(n1, n2)
        End Function
        
        Public Function Subtract(ByVal n1 As Integer, ByVal n2 As Integer) As Integer Implements IInstanceContextCalculator.Subtract
            Return MyBase.Channel.Subtract(n1, n2)
        End Function
        
        Public Function Multiply(ByVal n1 As Integer, ByVal n2 As Integer) As Integer Implements IInstanceContextCalculator.Multiply
            Return MyBase.Channel.Multiply(n1, n2)
        End Function
        
        Public Function Divide(ByVal n1 As Integer, ByVal n2 As Integer) As Integer Implements IInstanceContextCalculator.Divide
            Return MyBase.Channel.Divide(n1, n2)
        End Function
        
        Public Function GetInstanceContextInfo() As String Implements IInstanceContextCalculator.GetInstanceContextInfo
            Return MyBase.Channel.GetInstanceContextInfo
        End Function
    End Class
End Namespace
