!IFNDEF CORSDK
CORSDK=..\..\..\..\..\..
!ENDIF

#assumes file is \com20sdk\QuickStart\master.mak
!include $(CORSDK)\QuickStart\master.mak

# Import DLLs
_IMPORTS= /r:System.Net.dll

all:  chat.exe DateTimeServer.exe DateTimeClient.exe