'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.2914.16
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

Namespace TerraService
    
    <System.Web.Services.WebServiceBindingAttribute(Name:="TerraServiceSoap", [Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class TerraService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.Url = "http://terraservice.net/TerraService.asmx"
        End Sub
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/ConvertLonLatPtToNearestPlace", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConvertLonLatPtToNearestPlace(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal point As LonLatPt) As String
            Dim results() As Object = Me.Invoke("ConvertLonLatPtToNearestPlace", New Object() {point})
            Return CType(results(0),String)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginConvertLonLatPtToNearestPlace(ByVal point As LonLatPt, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ConvertLonLatPtToNearestPlace", New Object() {point}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndConvertLonLatPtToNearestPlace(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/ConvertLonLatPtToUtmPt", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConvertLonLatPtToUtmPt(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal point As LonLatPt) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> UtmPt
            Dim results() As Object = Me.Invoke("ConvertLonLatPtToUtmPt", New Object() {point})
            Return CType(results(0),UtmPt)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginConvertLonLatPtToUtmPt(ByVal point As LonLatPt, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ConvertLonLatPtToUtmPt", New Object() {point}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndConvertLonLatPtToUtmPt(ByVal asyncResult As System.IAsyncResult) As UtmPt
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),UtmPt)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/ConvertUtmPtToLonLatPt", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConvertUtmPtToLonLatPt(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal utm As UtmPt) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> LonLatPt
            Dim results() As Object = Me.Invoke("ConvertUtmPtToLonLatPt", New Object() {utm})
            Return CType(results(0),LonLatPt)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginConvertUtmPtToLonLatPt(ByVal utm As UtmPt, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ConvertUtmPtToLonLatPt", New Object() {utm}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndConvertUtmPtToLonLatPt(ByVal asyncResult As System.IAsyncResult) As LonLatPt
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),LonLatPt)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/ConvertPlaceToLonLatPt", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConvertPlaceToLonLatPt(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal place As Place) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> LonLatPt
            Dim results() As Object = Me.Invoke("ConvertPlaceToLonLatPt", New Object() {place})
            Return CType(results(0),LonLatPt)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginConvertPlaceToLonLatPt(ByVal place As Place, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ConvertPlaceToLonLatPt", New Object() {place}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndConvertPlaceToLonLatPt(ByVal asyncResult As System.IAsyncResult) As LonLatPt
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),LonLatPt)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/CountPlacesInRect", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CountPlacesInRect(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal upperleft As LonLatPt, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal lowerright As LonLatPt, ByVal ptype As PlaceType) As Integer
            Dim results() As Object = Me.Invoke("CountPlacesInRect", New Object() {upperleft, lowerright, ptype})
            Return CType(results(0),Integer)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginCountPlacesInRect(ByVal upperleft As LonLatPt, ByVal lowerright As LonLatPt, ByVal ptype As PlaceType, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CountPlacesInRect", New Object() {upperleft, lowerright, ptype}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndCountPlacesInRect(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetAreaFromPt", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAreaFromPt(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal center As LonLatPt, ByVal theme As Theme, ByVal scale As Scale, ByVal displayPixWidth As Integer, ByVal displayPixHeight As Integer) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> AreaBoundingBox
            Dim results() As Object = Me.Invoke("GetAreaFromPt", New Object() {center, theme, scale, displayPixWidth, displayPixHeight})
            Return CType(results(0),AreaBoundingBox)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetAreaFromPt(ByVal center As LonLatPt, ByVal theme As Theme, ByVal scale As Scale, ByVal displayPixWidth As Integer, ByVal displayPixHeight As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAreaFromPt", New Object() {center, theme, scale, displayPixWidth, displayPixHeight}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetAreaFromPt(ByVal asyncResult As System.IAsyncResult) As AreaBoundingBox
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AreaBoundingBox)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetAreaFromRect", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAreaFromRect(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal upperLeft As LonLatPt, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal lowerRight As LonLatPt, ByVal theme As Theme, ByVal scale As Scale) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> AreaBoundingBox
            Dim results() As Object = Me.Invoke("GetAreaFromRect", New Object() {upperLeft, lowerRight, theme, scale})
            Return CType(results(0),AreaBoundingBox)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetAreaFromRect(ByVal upperLeft As LonLatPt, ByVal lowerRight As LonLatPt, ByVal theme As Theme, ByVal scale As Scale, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAreaFromRect", New Object() {upperLeft, lowerRight, theme, scale}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetAreaFromRect(ByVal asyncResult As System.IAsyncResult) As AreaBoundingBox
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AreaBoundingBox)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetAreaFromTileId", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAreaFromTileId(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal id As TileId, ByVal displayPixWidth As Integer, ByVal displayPixHeight As Integer) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> AreaBoundingBox
            Dim results() As Object = Me.Invoke("GetAreaFromTileId", New Object() {id, displayPixWidth, displayPixHeight})
            Return CType(results(0),AreaBoundingBox)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetAreaFromTileId(ByVal id As TileId, ByVal displayPixWidth As Integer, ByVal displayPixHeight As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAreaFromTileId", New Object() {id, displayPixWidth, displayPixHeight}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetAreaFromTileId(ByVal asyncResult As System.IAsyncResult) As AreaBoundingBox
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AreaBoundingBox)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetLatLonMetrics", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLatLonMetrics(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal point As LonLatPt) As <System.Xml.Serialization.XmlArrayItemAttribute("ThemeBoundingBox", IsNullable:=false)> ThemeBoundingBox()
            Dim results() As Object = Me.Invoke("GetLatLonMetrics", New Object() {point})
            Return CType(results(0),ThemeBoundingBox())
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetLatLonMetrics(ByVal point As LonLatPt, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetLatLonMetrics", New Object() {point}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetLatLonMetrics(ByVal asyncResult As System.IAsyncResult) As ThemeBoundingBox()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ThemeBoundingBox())
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetPlaceFacts", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPlaceFacts(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal place As Place) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> PlaceFacts
            Dim results() As Object = Me.Invoke("GetPlaceFacts", New Object() {place})
            Return CType(results(0),PlaceFacts)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetPlaceFacts(ByVal place As Place, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPlaceFacts", New Object() {place}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetPlaceFacts(ByVal asyncResult As System.IAsyncResult) As PlaceFacts
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PlaceFacts)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetPlaceList", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPlaceList(ByVal placeName As String, ByVal MaxItems As Integer, ByVal imagePresence As Boolean) As <System.Xml.Serialization.XmlArrayItemAttribute("PlaceFacts", IsNullable:=false)> PlaceFacts()
            Dim results() As Object = Me.Invoke("GetPlaceList", New Object() {placeName, MaxItems, imagePresence})
            Return CType(results(0),PlaceFacts())
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetPlaceList(ByVal placeName As String, ByVal MaxItems As Integer, ByVal imagePresence As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPlaceList", New Object() {placeName, MaxItems, imagePresence}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetPlaceList(ByVal asyncResult As System.IAsyncResult) As PlaceFacts()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PlaceFacts())
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetPlaceListInRect", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPlaceListInRect(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal upperleft As LonLatPt, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal lowerright As LonLatPt, ByVal ptype As PlaceType, ByVal MaxItems As Integer) As <System.Xml.Serialization.XmlArrayItemAttribute("PlaceFacts", IsNullable:=false)> PlaceFacts()
            Dim results() As Object = Me.Invoke("GetPlaceListInRect", New Object() {upperleft, lowerright, ptype, MaxItems})
            Return CType(results(0),PlaceFacts())
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetPlaceListInRect(ByVal upperleft As LonLatPt, ByVal lowerright As LonLatPt, ByVal ptype As PlaceType, ByVal MaxItems As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPlaceListInRect", New Object() {upperleft, lowerright, ptype, MaxItems}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetPlaceListInRect(ByVal asyncResult As System.IAsyncResult) As PlaceFacts()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PlaceFacts())
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetTheme", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTheme(ByVal theme As Theme) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ThemeInfo
            Dim results() As Object = Me.Invoke("GetTheme", New Object() {theme})
            Return CType(results(0),ThemeInfo)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetTheme(ByVal theme As Theme, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTheme", New Object() {theme}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetTheme(ByVal asyncResult As System.IAsyncResult) As ThemeInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ThemeInfo)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetTileMetaFromLonLatPt", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTileMetaFromLonLatPt(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal point As LonLatPt, ByVal theme As Theme, ByVal scale As Scale) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> TileMeta
            Dim results() As Object = Me.Invoke("GetTileMetaFromLonLatPt", New Object() {point, theme, scale})
            Return CType(results(0),TileMeta)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetTileMetaFromLonLatPt(ByVal point As LonLatPt, ByVal theme As Theme, ByVal scale As Scale, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTileMetaFromLonLatPt", New Object() {point, theme, scale}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetTileMetaFromLonLatPt(ByVal asyncResult As System.IAsyncResult) As TileMeta
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TileMeta)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetTileMetaFromTileId", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTileMetaFromTileId(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal id As TileId) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> TileMeta
            Dim results() As Object = Me.Invoke("GetTileMetaFromTileId", New Object() {id})
            Return CType(results(0),TileMeta)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetTileMetaFromTileId(ByVal id As TileId, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTileMetaFromTileId", New Object() {id}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetTileMetaFromTileId(ByVal asyncResult As System.IAsyncResult) As TileMeta
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TileMeta)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://terraservice.net/terraserver/GetTile", RequestNamespace:="http://terraservice.net/terraserver/", ResponseNamespace:="http://terraservice.net/terraserver/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTile(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)> ByVal id As TileId) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)> Byte()
            Dim results() As Object = Me.Invoke("GetTile", New Object() {id})
            Return CType(results(0),Byte())
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function BeginGetTile(ByVal id As TileId, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTile", New Object() {id}, callback, asyncState)
        End Function
        
        <System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Function EndGetTile(ByVal asyncResult As System.IAsyncResult) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Byte())
        End Function
    End Class
    
    Public Class LonLatPt
        
        Public Lon As Double
        
        Public Lat As Double
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class ThemeInfo
        
        Public Theme As Theme
        
        Public Name As String
        
        Public Description As String
        
        Public Supplier As String
        
        Public LoScale As Scale
        
        Public HiScale As Scale
        
        Public ProjectionId As ProjectionType
        
        Public ProjectionName As String
        
        Public CopyrightNotice As String
    End Class
    
    Public Enum Theme
        
        Photo
        
        Topo
        
        Relief
    End Enum
    
    Public Enum Scale
        
        Scale1mm
        
        Scale2mm
        
        Scale4mm
        
        Scale8mm
        
        Scale16mm
        
        Scale32mm
        
        Scale63mm
        
        Scale125mm
        
        Scale250mm
        
        Scale500mm
        
        Scale1m
        
        Scale2m
        
        Scale4m
        
        Scale8m
        
        Scale16m
        
        Scale32m
        
        Scale64m
        
        Scale128m
        
        Scale256m
        
        Scale512m
        
        Scale1km
        
        Scale2km
        
        Scale4km
        
        Scale8km
        
        Scale16km
    End Enum
    
    Public Enum ProjectionType
        
        Geographic
        
        UtmNad27
        
        UtmNad83
    End Enum
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class PlaceFacts
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public Place As Place
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public Center As LonLatPt
        
        Public AvailableThemeMask As Themes
        
        Public PlaceTypeId As PlaceType
        
        Public Population As Integer
    End Class
    
    Public Class Place
        
        Public City As String
        
        Public State As String
        
        Public Country As String
    End Class
    
    <System.FlagsAttribute()>  _
    Public Enum Themes
        
        Photo = 1
        
        Topo = 2
        
        Relief = 4
    End Enum
    
    Public Enum PlaceType
        
        UnknownPlaceType
        
        AirRailStation
        
        BayGulf
        
        CapePeninsula
        
        CityTown
        
        HillMountain
        
        Island
        
        Lake
        
        OtherLandFeature
        
        OtherWaterFeature
        
        ParkBeach
        
        PointOfInterest
        
        River
    End Enum
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class ThemeBoundingBox
        
        Public Theme As Theme
        
        Public ThemeName As String
        
        Public Sparseness As Integer
        
        Public LoScale As Scale
        
        Public HiScale As Scale
        
        Public ProjectionId As ProjectionType
        
        Public ProjectionName As String
        
        Public WestLongitude As Double
        
        Public NorthLatitude As Double
        
        Public EastLongitude As Double
        
        Public SouthLatitude As Double
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class OverlappingThemeInfo
        
        Public LocalTheme As Boolean
        
        Public Theme As Theme
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public Point As LonLatPt
        
        Public ThemeName As String
        
        Public Capture As Date
        
        Public ProjectionId As ProjectionType
        
        Public LoScale As Scale
        
        Public HiScale As Scale
        
        Public Url As String
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class LonLatPtOffset
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public Point As LonLatPt
        
        Public XOffset As Integer
        
        Public YOffset As Integer
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class TileId
        
        Public Theme As Theme
        
        Public Scale As Scale
        
        Public Scene As Integer
        
        Public X As Integer
        
        Public Y As Integer
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class TileMeta
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public Id As TileId
        
        Public TileExists As Boolean
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public NorthWest As LonLatPt
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public NorthEast As LonLatPt
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public SouthWest As LonLatPt
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public SouthEast As LonLatPt
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public Center As LonLatPt
        
        Public Capture As Date
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class AreaCoordinate
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public TileMeta As TileMeta
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public Offset As LonLatPtOffset
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class AreaBoundingBox
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public NorthWest As AreaCoordinate
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public NorthEast As AreaCoordinate
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public SouthWest As AreaCoordinate
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public SouthEast As AreaCoordinate
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public Center As AreaCoordinate
        
        Public NearestPlace As String
        
        <System.Xml.Serialization.XmlArrayItemAttribute("OverlappingThemeInfo", IsNullable:=false)>  _
        Public OverlappingThemeInfos() As OverlappingThemeInfo
    End Class
    
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://terraservice.net/terraserver/")>  _
    Public Class UtmPt
        
        Public Zone As Integer
        
        Public X As Double
        
        Public Y As Double
    End Class
End Namespace
