all: ErrorHandler \
     OwnerDrawListBox \
     ThreadMarshal 

ErrorHandler::
	cd ErrorHandler 
	- nmake 
	cd ..

OwnerDrawListBox::
	cd OwnerDrawListBox
	- nmake 
	cd ..
        
ThreadMarshal::
	cd ThreadMarshal
	- nmake 
	cd ..
