!IFNDEF CORSDK
#assumes that we are in com20sdk\quickstart\aspplus\samples\webforms\intro
CORSDK=..\..\..\..\..
!ENDIF

#tell nmake where to find the master rules for building COM+ applications
#assumes file is \com20sdk\QuickStart\master.mak
!include $(CORSDK)\QuickStart\master.mak

all: ButtonCtl CheckedListBoxCtl ComboboxCtl DateTimePickerCtl LinkLabelCtl \
        ListBoxCtl ScrollBarCtl StatusBarCtl TabControlCtl ToolTipCtl TrackBarCtl  \
        TreeViewCtl UpDownCtl ProgressBarCtl

ButtonCtl::
	cd ButtonCtl
	$(_CONTINUE) nmake 
	cd ..

CheckedListBoxCtl::
	cd CheckedListBoxCtl
	$(_CONTINUE) nmake 
	cd ..

ComboboxCtl::
	cd ComboboxCtl
	$(_CONTINUE) nmake 
	cd ..

DateTimePickerCtl::
	cd DateTimePickerCtl
	$(_CONTINUE) nmake 
	cd ..
        
LinkLabelCtl::
	cd LinkLabelCtl
	$(_CONTINUE) nmake 
	cd ..

ListBoxCtl::
        cd ListBoxCtl
	$(_CONTINUE) nmake 
	cd ..
        
ScrollBarCtl::
        cd ScrollBarCtl
	$(_CONTINUE) nmake 
	cd ..
        
StatusBarCtl::
        cd StatusBarCtl
	$(_CONTINUE) nmake 
	cd ..
        
TabControlCtl::
        cd TabControlCtl
	$(_CONTINUE) nmake 
	cd ..
        
ToolTipCtl::
        cd ToolTipCtl
	$(_CONTINUE) nmake 
	cd ..

TrackBarCtl::
        cd TrackBarCtl
	$(_CONTINUE) nmake 
	cd ..

TreeViewCtl::
        cd TreeViewCtl
	$(_CONTINUE) nmake 
	cd ..
        
UpDownCtl::
        cd UpDownCtl
	$(_CONTINUE) nmake 
	cd ..
        
ProgressBarCtl::
        cd ProgressBarCtl
	$(_CONTINUE) nmake 
	cd ..
        

