'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version:2.0.41112.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

<Assembly: Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope:="member", Target:="Microsoft.Samples.Windows.Forms.TaskPaneTest.MySettings.get_Default():Microsoft.S"& _ 
    "amples.Windows.Forms.TaskPaneTest.MySettings")> 


Partial NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Private Shared defaultInstance As MySettings = New MySettings
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            Return defaultInstance
        End Get
    End Property
End Class
