!include ..\..\..\master.mak

_OUTDIR=..\bin

_IMPORTS=/reference:..\Bin\CompCS.dll /reference:..\Bin\CompVB.dll /reference:..\Bin\CompVC.dll /reference:System.WinForms.dll

All: ClientWinForms

ClientWinForms: ClientWinForms.exe

ClientWinForms.exe: ClientWinForms.vb