//------------------------------------------------------------------------------
/// <autogenerated>
///     This class was generated by a tool.
///     Runtime Version: 1.0.2204.14
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

namespace DataTypesService {
    using System.Xml.Serialization;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    public class DataTypes : System.Web.Services.Protocols.SoapClientProtocol {
        public DataTypes() {
            this.Url = "http://localhost/QuickStart/aspplus/samples/services/DataTypes/DataTypes.asmx";
        }
        
        [System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/SayHello")]
        public string SayHello() {
            object[] results = this.Invoke("SayHello", new object[0]);
            return (string)(results[0]);
        }
        public System.IAsyncResult BeginSayHello(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SayHello", new object[0], callback, asyncState);
        }
        public string EndSayHello(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return (string)(results[0]);
        }
        [System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/SayHelloName")]
        public string SayHelloName( string name) {
            object[] results = this.Invoke("SayHelloName", new object[] {name});
            return (string)(results[0]);
        }
        public System.IAsyncResult BeginSayHelloName(string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SayHelloName", new object[] {name}, callback, asyncState);
        }
        public string EndSayHelloName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return (string)(results[0]);
        }
        [System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/GetIntArray"), 
        System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, ArrayType=System.Xml.Serialization.XmlArrayType.Soap), 
        System.Xml.Serialization.XmlArrayItemAttribute("int", IsNullable=false)]
        public int[] GetIntArray() {
            object[] results = this.Invoke("GetIntArray", new object[0]);
            return (int[])(results[0]);
        }
        public System.IAsyncResult BeginGetIntArray(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetIntArray", new object[0], callback, asyncState);
        }
        public int[] EndGetIntArray(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return (int[])(results[0]);
        }
        [System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/GetMode")]
        public Mode GetMode() {
            object[] results = this.Invoke("GetMode", new object[0]);
            return (Mode)(results[0]);
        }
        public System.IAsyncResult BeginGetMode(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMode", new object[0], callback, asyncState);
        }
        public Mode EndGetMode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return (Mode)(results[0]);
        }
        [System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/GetOrder")]
        public Order GetOrder() {
            object[] results = this.Invoke("GetOrder", new object[0]);
            return (Order)(results[0]);
        }
        public System.IAsyncResult BeginGetOrder(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrder", new object[0], callback, asyncState);
        }
        public Order EndGetOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return (Order)(results[0]);
        }
        [System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/GetOrders"), 
        System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, ArrayType=System.Xml.Serialization.XmlArrayType.Soap), 
        System.Xml.Serialization.XmlArrayItemAttribute("Order", IsNullable=true)]
        public Order[] GetOrders() {
            object[] results = this.Invoke("GetOrders", new object[0]);
            return (Order[])(results[0]);
        }
        public System.IAsyncResult BeginGetOrders(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrders", new object[0], callback, asyncState);
        }
        public Order[] EndGetOrders(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return (Order[])(results[0]);
        }
        
    }
    [System.Xml.Serialization.XmlRootAttribute("result", Namespace="http://tempuri.org/", IsNullable=false)]
    public enum Mode {
        [System.Xml.Serialization.XmlEnumAttribute("On")]
        ON,
        
        Off,
        
    }
    [System.Xml.Serialization.XmlRootAttribute("result", Namespace="http://tempuri.org/", IsNullable=true)]
    public class Order {
        
        public int OrderID;
        
        public System.Double Price;
        
    }
}
