!IFNDEF CORSDK
#assumes that we are in com20sdk\quickstart\aspplus\samples\webforms\intro
CORSDK=..\..\..\..
!ENDIF

#tell nmake where to find the master rules for building COM+ applications
#assumes file is \com20sdk\QuickStart\master.mak
!include $(CORSDK)\QuickStart\master.mak

all: DataSetMapXMLData DataSetMapXSDSchema DOMInterfaceXmlDocument EditingXmlDocument LoadDataSetXMLData \
LoadXmlDocument NavigateXmlDocument QueryXmlDocumentXPath ReadXmlFile ReadXmlStream SaveDataSetMapXSDSchema SaveDataSetXMLData \
SaveXmlDocument StreamXmlDocument TransformXml ValidationReadingXML WriteXmlFile

DataSetMapXMLData::
	cd DataSetMapXMLData
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

DataSetMapXSDSchema::
	cd DataSetMapXSDSchema
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

DOMInterfaceXmlDocument::
	cd DOMInterfaceXmlDocument
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

EditingXmlDocument::
	cd EditingXmlDocument
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

LoadDataSetXMLData::
	cd LoadDataSetXMLData
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

LoadXmlDocument::
	cd LoadXmlDocument
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

NavigateXmlDocument::
	cd NavigateXmlDocument
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

QueryXmlDocumentXPath::
	cd QueryXmlDocumentXPath
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

ReadXmlFile::
	cd ReadXmlFile
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

ReadXmlStream::
	cd ReadXmlStream
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

SaveDataSetMapXSDSchema::
	cd SaveDataSetMapXSDSchema
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

SaveDataSetXMLData::
	cd SaveDataSetXMLData
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

SaveXmlDocument::
	cd SaveXmlDocument
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

StreamXmlDocument::
	cd StreamXmlDocument
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

TransformXml::
	cd TransformXml
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

ValidationReadingXML::
	cd ValidationReadingXML
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..

WriteXmlFile::
	cd WriteXmlFile
	$(_CONTINUE) nmake 
	cd vb
	$(_CONTINUE) nmake 
    cd ..\..
