all: Brushes \
     Images  \
     Pens    \
     Text

Brushes::
	cd Brushes
	nmake 
	cd ..

Images::
	cd Images
	nmake 
	cd ..
        
Pens::
	cd Pens
	nmake 
	cd ..

Text::
	cd Text
	nmake 
	cd ..

